build:
  stage: build
  script:
    - docker build -t ${CI_REGISTRY}/${CI_PROJECT_PATH} .

post-build:
  stage: .post
  script:
    - docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY <<< $CI_REGISTRY_PASSWORD
    - docker push ${CI_REGISTRY}/${CI_PROJECT_PATH}