build-job:
  stage: build
  script:
    - docker build -t netdox .

push-job:
  stage: push
  script:
    - docker -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push ${CI_REGISTRY}/allette/devops/network-documentation/netdox