before_script:
  - python3 -m virtualenv venv
  - source venv/bin/activate
  - python3 -m pip install tox mypy wheel

stages:
  - test
  - build

tox:
  stage: test
  script: 
    - 'tox -- --cov'

mypy:
  stage: test
  allow_failure: true
  script:
    - 'mypy --install-types --non-interactive src/netdox'

build:
  stage: build
  only: 
    - tags
  script:
    - python3 setup.py bdist_wheel

  artifacts:
    paths:
      - dist/*.whl