before_script:
  - python3 -m virtualenv venv
  - source venv/bin/activate
  - python3 -m pip install tox mypy

stages:
  - test
  - build

tox:
  stage: test
  script: 
    - tox -- --cov --cov-report xml

  artifacts:
    reports:
      cobertura: coverage.xml

mypy:
  stage: test
  allow_failure: true
  script:
    - 'mypy --namespace-packages src/netdox'

build:
  stage: build
  only: 
    - tags
  script:
    - python3 setup.py bdist_wheel

  artifacts:
    paths:
      - dist/*.whl