workflow:
  rules:
    - if: tags

before_script:
  - python3 -m virtualenv venv
  - source venv/bin/activate

build:
  script:
  - python3 setup.py bdist_wheel

  artifacts:
    paths:
    - dist/*.whl

test:
  script: 
  - pip install tox
  - tox -- --cov --cov-report xml

  artifacts:
    reports:
      cobertura: coverage.xml