build:
  stage: build
  script:
    - docker build -t ${CI_REGISTRY}/allette/devops/network-documentation/netdox .

post-build:
  stage: .post
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push ${CI_REGISTRY}/allette/devops/network-documentation/netdox