[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
testpaths = ['tests']

[tool.coverage.run]
source = ['netdox']

[tool.coverage.report]
skip_covered = true
show_missing = true
exclude_lines = [
    'if TYPE_CHECKING:',
    'raise NotImplementedError',
    'def _.*',
    '@abstractmethod',
    '@property',
]
omit = [
    '*/netdox/cli.py',
    '*/netdox/refresh.py',
    '*/netdox/serve.py',
    '*/netdox/pageseeder.py',
]

[tool.tox]
legacy_tox_ini = """
[tox]
envlist = py39

[testenv]
deps = pytest
commands = pytest
"""