#!/usr/bin/env bash

## Serve webhook listener
function serve {
    gunicorn --reload -b '0.0.0.0:8080' -t 900 serve:app
}

## Refresh DNS data and upload to PageSeeder
function refresh {
    if [[ -z /etc/ext/log ]]; then mkdir /etc/ext/log; fi
    _refresh 2>&1 | tee "/etc/ext/log/refresh-$(date +%F-T%T).log"
}
function _refresh {
    for dir in /opt/app/out/*; do
        rm -rf ${dir}/*
    done

    echo '[INFO][netdox] Refreshing DNS...'

    if python3 refresh.py
        then
            echo '[INFO][netdox] Python exited successfully. Beginning PageSeeder upload...'
            cd /opt/app/out
            zip -r -q netdox-src.zip *
            cd /opt/app
            if ant -lib /opt/ant/lib
                then
                    echo '[INFO][netdox] Upload successful. Running post-upload cleanup...'
                    python3 cleanup.py
                    echo '[INFO][netdox] Refresh complete.'
                else
                    echo '[ERROR][netdox] Upload exited with non-zero status. Storing psml for debugging...'
                    cp /opt/app/out/netdox-src.zip /etc/ext/psml.zip
            fi
        else
            echo '[ERROR][netdox] Python exited with non-zero status. Cancelling upload...'
    fi

    cp /opt/app/src/forward.json /etc/ext/forward.json &> /dev/null
    cp /opt/app/src/reverse.json /etc/ext/reverse.json &> /dev/null
}

## Initialise container to allow other processes to run
function init {
    echo "[INFO][netdox] Initalising container as: $(id)"
    
    [[ -d /etc/ext/log ]] || mkdir /etc/ext/log

    cp /etc/ext/forward.json /opt/app/src/forward.json &> /dev/null
    cp /etc/ext/reverse.json /opt/app/src/reverse.json &> /dev/null

    # make all scripts executable
    chmod 777 /opt/app/*
    
    # decrypt authentication details
    ./crypto.sh decrypt $(printf authivpassphrase | xxd -p) "/etc/ext/cfg/authentication.bin" "/opt/app/src/authentication.json"
    
    # copy any unecrypted cfg files
    for file in /etc/ext/cfg/*.json; do
        cp $file /opt/app/src/$(basename $file) &> /dev/null
    done

    for initscript in plugins/*/init.sh; do
        chmod 777 $initscript
        $initscript
    done

    if python3 init.py
        then
            echo '[INFO][netdox] Python initialisation successful.'
        else
            echo '[ERROR][netdox] Python initialisation unsuccessful. Terminating...'
            exit 1
    fi

    crontab <<< '15 6 * * * "/opt/app/netdox refresh"'
}


methods=("init" "refresh" "serve")
for arg in "$@"; do
    if [[ ${methods[@]} =~ $arg ]]
        then case $arg in
            serve)
                serve &
                ;;
            *)
                $arg
                ;;
        esac
    elif [[ $arg == 'start' ]]
        then if init
            then serve
        fi
    fi
done